import { FlatCompat } from "@eslint/eslintrc";
import tseslint from "typescript-eslint";

/**
 * Lint config.
 *
 * `npm run lint` was in package.json without ESLint installed or any config, so
 * it did nothing but prompt interactively - which also meant the
 * `eslint-disable` comments scattered through src/lib were silently inert.
 * They are gone now; the `any`s they were suppressing are gone too.
 */
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default tseslint.config(
  // next-env.d.ts is generated by Next on every build.
  { ignores: [".next/**", "node_modules/**", "src/db/migrations/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // The point of typing the database layer was to stop `any` creeping back
      // in, so this is an error rather than a warning.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
);
